[build-system]
requires = [
    "setuptools>=59.6,<60; python_version == '3.6'",
    "setuptools>=61,<68; python_version == '3.7'",
    "setuptools>=75; python_version >= '3.8'",
    "wheel>=0.37,<0.38; python_version == '3.6'",
    "wheel>=0.38; python_version >= '3.7'",
    "pybind11>=2.10.4,<2.13; python_version < '3.8'",
    "pybind11>=3.0.4,<4; python_version >= '3.8'",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp{39,310,311,312,313,314,314t}-win*"
test-command = "python {project}/sample/sample.py"

[tool.cibuildwheel.windows]
archs = ["auto64"]
