name: Build sysproxy binding

on: [push, pull_request]

jobs:
  build_sysproxy:
    name: ${{ matrix.os }} Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python --version

      - name: Install wheel
        run: python -m pip install wheel

      - name: Generate source distribution
        run: python setup.py sdist

      - name: Generate wheel distribution
        run: python setup.py bdist_wheel

      - name: Install from source
        run: python setup.py install

      - name: Run sample.py
        run: python sample/sample.py
